### PR TITLE
Added USER_TWEETS fetching

### LINKED ISSUE #367: Is it possible to join the user timeline?
I need to get the user's timeline and filter it by different types, such as tweets, retweets, likes or replies, and then paginate through the cursor

### LINKED ISSUE #368: Implement fetching of user timeline

### PR DESCRIPTION
**Pull request by omarcinkonis**
Let me know if the method should be called 'tweets' or 'timeline'

Closes #367
Closes #368

### CODE REVIEW

**Comment by Rishikant181** [comment]
I think it makes sense to use 'timeline' here, instead of 'tweets', since this library is user-facing and serves as an abstraction over rettiwt-core, hiding low level details.

**Comment by omarcinkonis** [comment]
Updated, tested

**Comment by Rishikant181** [comment]
Okay I'll be merging it in the evening. I'm afk now :(

**Comment by Rishikant181** [comment]
@omarcinkonis There is an issue with fetching the timeline when a cursor is provided. The same data is returned over and over again when using a cursor. I'm looking into it right now.

**Pull request merged**
